Bumped @playwright/test
no issue

- fixed tests failing locally because of a Chromium issue, log included below to help future searches

```
ProtocolError: Protocol error (Browser.getVersion): Internal server error, session closed.
    at /Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/chromium/crConnection.js:135:16
    at new Promise (<anonymous>)
    at CRSession.send (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/chromium/crConnection.js:131:12)
    at Function.connect (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/chromium/crBrowser.js:51:35)
    at Chromium._connectToTransport (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/chromium/chromium.js:130:33)
    at Chromium._innerLaunch (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/browserType.js:125:32)
    at Chromium._innerLaunchWithRetries (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/browserType.js:84:14)
    at ProgressController.run (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/progress.js:91:22)
    at Chromium.launchPersistentContext (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/browserType.js:75:21)
    at launchApp (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/launchApp.js:36:19)
    at openTraceViewerApp (/Users/kevin/code/Koenig/node_modules/playwright-core/lib/server/trace/viewer/traceViewer.js:140:7)
    at UIMode.showUI (/Users/kevin/code/Koenig/node_modules/playwright/lib/runner/uiMode.js:141:20)
    at runUIMode (/Users/kevin/code/Koenig/node_modules/playwright/lib/runner/uiMode.js:243:5)
    at Runner.uiAllTests (/Users/kevin/code/Koenig/node_modules/playwright/lib/runner/runner.js:102:12)
    at runTests (/Users/kevin/code/Koenig/node_modules/playwright/lib/cli.js:129:55)
    at t.<anonymous> (/Users/kevin/code/Koenig/node_modules/playwright/lib/cli.js:42:7) {
  type: 'closed',
  method: 'Browser.getVersion',
  logs: '\n' +
    '<launching> /Users/kevin/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --enable-use-zoom-for-dsf=false --no-sandbox --app=data:text/html, --window-size=1280,800 --test-type= --user-data-dir=/var/folders/jm/5fkxt6616r54868pdnj5kb4c0000gn/T/playwright_chromiumdev_profile-XgVHymH4MFv2 --remote-debugging-pipe about:blank\n' +
    '<launched> pid=9603\n' +
    '[pid=9603][err] [9603:259:1030/130940.186737:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.\n' +
    '[pid=9603][err] [1030/130940.469869:WARNING:in_range_cast.h(38)] value -634136515 out of range\n' +
    '[pid=9603][err] [1030/130940.656123:WARNING:in_range_cast.h(38)] value -634136515 out of range\n' +
    '[pid=9603][err] [1030/130940.667021:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)'
}
```